name: Validate manifest
on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - '**.png'
      - '**.json'
      - '**_manifest.json'

permissions:
  contents: read

jobs:
  update-manifest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR
        uses: actions/checkout@v5
        with:
          fetch-depth: 1
          persist-credentials: false

      - name: Ensure images directory exists
        run: mkdir -p images

      - name: Install uv
        run: pipx install uv

      - name: Check manifest
        run: uvx git+https://github.com/arkutils/obelisk-manager.git check images/
